---
abstract: 'Japanese Lorem Ipsum generator'
author:
  - 'ITO Nobuaki <dayflower@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.2, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Lorem-JA
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Text::Lorem::JA:
    file: lib/Text/Lorem/JA.pm
    version: 0.02
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/dayflower/p5-Text-Lorem-JA/issues
  homepage: https://github.com/dayflower/p5-Text-Lorem-JA
  repository: git://github.com/dayflower/p5-Text-Lorem-JA.git
version: 0.02
